seo:
  image: /images/og-image.png

header:
  heading: Fulldev UI
  variant: base
  links:
    - text: Docs
      href: /overview/introduction
    - text: Components
      href: /typography/heading
    - text: Blocks
      href: /blocks
    - text: Showcase
      href: /showcase
  search:
    icon: search
    variant: soft
  buttons:
    - href: https://github.com/fulldotdev/ui
      target: _blank
      aria-label: GitHub
      icon: brand-github
    - href: https://discord.gg/vXZqMbadm8
      target: _blank
      aria-label: Discord
      icon: brand-discord
  drawer:
    - links:
        - text: Docs
          href: /overview/introduction
        - text: Components
          href: /typography/heading
        - text: Blocks
          href: /blocks
    - heading: Overview
      links:
        - text: Introduction
          href: /overview/introduction
        - text: Installation
          href: /overview/installation
        - text: Integration
          href: /overview/integration
        - text: Theming
          href: /overview/theming
        - text: Frameworks
          href: /overview/frameworks
        - text: Showcase
          href: /showcase
    - heading: Typography
      folder: typography
    - heading: Base
      folder: base
    - heading: Structure
      folder: structure
