version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      data-slot:
        patterns:
          - "@data-slot/*"
      astro:
        patterns:
          - "astro"
          - "@astrojs/*"
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
