tabWidth: 2
parser: 'typescript'
semi: false
singleQuote: true
trailingComma: 'es5'
singleAttributePerLine: true
plugins:
  - 'prettier-plugin-css-order'
  - 'prettier-plugin-astro'
  - 'prettier-plugin-tailwindcss'
  - 'prettier-plugin-organize-imports'
  - 'prettier-plugin-astro-organize-imports'
printWidth: 120
tailwindStylesheet: './src/styles/globals.css'
tailwindConfig: './tailwind.config.js'
tailwindFunctions:
  - clsx
  - cn
  - tw
tailwindPreserveWhitespace: true
tailwindPreserveDuplicates: false
overrides:
  - files: '*.ts'
    options:
      parser: 'typescript'
  - files: '*.astro'
    options:
      parser: 'astro'
  - files: '*.css'
    options:
      parser: 'css'
  - files: '*.pcss'
    options:
      parser: 'css'
  - files: '*.scss'
    options:
      parser: 'scss'
  - files: '*.mdx'
    options:
      parser: 'mdx'
      singleAttributePerLine: false
  - files: '*.yml'
    options:
      parser: 'yaml'