paths:
  uploads: public/images
  static: public

collection_groups:
  - heading: Collections
    collections:
      - pages
      - posts
      - products
      - categories
      - docs
      - jobs
  - heading: Data
    collections:
      - globals

collections_config:
  pages:
    path: src/collections/pages
    url: /[full_slug]/
    _enabled_editors:
      - visual
      - content
    schemas:
      default:
        remove_extra_inputs: false
        remove_empty_inputs: true
        hide_extra_inputs: true
        path: node_modules/fulldev-ui/src/schemas/page.md
  posts:
    path: src/collections/posts
    url: /blog/[full_slug]/
    _enabled_editors:
      - content
      - visual
    schemas:
      default:
        remove_extra_inputs: false
        remove_empty_inputs: true
        hide_extra_inputs: true
        path: node_modules/fulldev-ui/src/schemas/post.md
  products:
    path: src/collections/products
    url: /producten/[full_slug]/
    _enabled_editors:
      - content
      - visual
    schemas:
      default:
        path: node_modules/fulldev-ui/src/schemas/product.md
  categories:
    path: src/collections/categories
    url: /categorieen/[full_slug]/
    _enabled_editors:
      - content
      - visual
    schemas:
      default:
        path: node_modules/fulldev-ui/src/schemas/category.md
  docs:
    path: src/collections/docs
    url: /docs/[full_slug]/
    _enabled_editors:
      - content
      - visual
    schemas:
      default:
        path: node_modules/fulldev-ui/src/schemas/doc.md
  jobs:
    path: src/collections/jobs
    url: /vacatures/[full_slug]/
    _enabled_editors:
      - content
      - visual
    schemas:
      default:
        path: node_modules/fulldev-ui/src/schemas/job.md
  globals:
    path: src/collections/globals
    disable_url: true
    _enabled_editors:
      - data

_inputs:
  head:
    label: SEO / Settings
    type: object
    options:
      empty_type: object
      structures:
        remove_empty_inputs: true
        hide_extra_inputs: true
        values:
          - label: SEO / Settings
            value:
              title:
              description:
              image:
              code:
  head.title:
    label: SEO title
    comment: 50-60 characters
  head.description:
    label: SEO description
    comment: 50-120 characters
  categories:
    type: multiselect
    label: Categorieën
    options:
      values: collections.pages
  children:
    type: multiselect
    label: Subcategorieën
    options:
      values: collections.pages
  siblings:
    type: multiselect
    label: Aanbevolen pagina's
    options:
      values: collections.pages
  href:
    type: url
    label: Link
  rating.value:
    label: Rating
    type: range
    options:
      min: 0
      max: 5
      step: 0.1
  head.image:
    type: image
    label: Image
    comment: Visible when you share a link of the page
    options:
      accepts_mime_types: image/jpeg,image/jpg,image/png,image/webp
      mime_type: image/png
      resize_style: contain
      width: 1200
      height: 640
  images:
    type: array
    cascade: true
  images[*]:
    type: image
    options:
      accepts_mime_types: image/jpeg,image/jpg,image/png,image/webp
      mime_type: image/webp
      resize_style: contain
      width: 1920
      height: 1920
  image:
    type: image
    label: Afbeelding
    options:
      accepts_mime_types: image/jpeg,image/jpg,image/png,image/webp
      mime_type: image/webp
      resize_style: contain
      width: 1920
      height: 1920
  list:
    type: array
  list[*]:
    type: text
  hidden:
    label: Hide
    type: switch
  soldout:
    label: Sold out
    type: switch
  draft:
    label: Draft
    type: switch
  order:
    label: Volgorde
    type: number
  paragraph:
    type: textarea
    label: Tekst
  text:
    type: textarea
    label: Tekst
  button.text:
    type: text
  options:
    type: array
    label: Opties
  options[*]:
    type: text
  variations:
    type: array
    label: Variations
  sizes:
    type: array
    label: Sizes
  sizes[*]:
    type: text
  logo:
    type: image
    cascade: true
    options:
      accepts_mime_types: image/jpeg,image/jpg,image/png,image/webp
      mime_type: image/webp
      resize_style: contain
      width: 260
      height: 32
  rating:
    type: range
    options:
      min: 0
      max: 5
      step: 0.1
    label: Rating
  price:
    type: number
    label: Prijs
  presets:
    hidden: true
  component:
    hidden: true
  dark:
    hidden: true
  name:
    hidden: true
  color:
    hidden: true
  layout:
    hidden: true
  position:
    hidden: true
  scheme:
    hidden: true
  hue:
    hidden: true
  align:
    hidden: true
  frame:
    hidden: true
  variant:
    hidden: true
  content:
    type: html
_editables:
  content:
    allow_custom_markup: false
    remove_custom_markup: false
    bold: true
    bulletedlist: true
    format: p h1 h2 h3 h4 h5 h6
    italic: true
    link: true
    numberedlist: true
    redo: true
    table: true
    underline: true
    undo: true
    image: true
    image_size_attributes: true
    mime_type: image/webp
    resize_style: contain
    width: 1920
    height: 1920
