paths:
  static: public
  uploads: public/images

collection_groups:
  - heading: Content
    collections:
      - pages
      - records
  - heading: Settings
    collections:
      - layouts

collections_config:
  pages:
    path: src/content/pages
    url: /[full_slug]/
    disable_add_folder: true
    _enabled_editors:
      - visual
      - content
    schemas:
      page:
        remove_extra_inputs: false
        remove_empty_inputs: true
        hide_extra_inputs: true
        path: schemas/page.md
      job:
        remove_extra_inputs: false
        remove_empty_inputs: true
        hide_extra_inputs: true
        path: schemas/job.md
      jobs:
        remove_extra_inputs: false
        remove_empty_inputs: true
        hide_extra_inputs: true
        path: schemas/jobs.md
      post:
        remove_extra_inputs: false
        remove_empty_inputs: true
        hide_extra_inputs: true
        path: schemas/post.md
  records:
    path: src/content/records
    name: Records
    disable_url: true
    disable_add_folder: true
    _enabled_editors:
      - data
  layouts:
    path: src/content/layouts
    name: Layouts
    icon: web
    disable_url: true
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
    _enabled_editors:
      - data
_inputs:
  pages:
    type: multiselect
    label: Categorieën
    options:
      values: collections.pages
  categories:
    type: multiselect
    label: Categorieën
    options:
      values: collections.pages
  href:
    type: url
    label: Link
  rating:
    label: Rating
    type: range
    options:
      min: 0
      max: 5
      step: 0.1
  head:
    label: SEO / Settings
  head.title:
    label: SEO title
    comment: 50-60 characters
  head.description:
    label: SEO description
    comment: 50-120 characters
  head.image:
    type: image
    label: Image
    comment: Visible when you share a link of the page
    options:
      accepts_mime_types: image/jpeg,image/jpg,image/png,image/webp
      mime_type: image/png
      resize_style: contain
      width: 1200
      height: 640
  images:
    type: array
    cascade: true
  images[*]:
    type: image
    options:
      accepts_mime_types: image/jpeg,image/jpg,image/png,image/webp
      mime_type: image/webp
      resize_style: contain
      width: 1920
      height: 1920
  image:
    type: image
    label: Afbeelding
    options:
      accepts_mime_types: image/jpeg,image/jpg,image/png,image/webp
      mime_type: image/webp
      resize_style: contain
      width: 1920
      height: 1920
  list:
    type: array
  list[*]:
    type: text
  hidden:
    label: Hide
    type: switch
  soldout:
    label: Sold out
    type: switch
  draft:
    label: Draft
    type: switch
  order:
    label: Volgorde
    type: number
  paragraph:
    type: textarea
    label: Tekst
  text:
    type: textarea
    label: Tekst
  button.text:
    type: text
  options:
    type: array
    label: Opties
  options[*]:
    type: text
  variations:
    type: array
    label: Variations
  sizes:
    type: array
    label: Sizes
  sizes[*]:
    type: text
  logo:
    type: image
    cascade: true
    options:
      accepts_mime_types: image/jpeg,image/jpg,image/png,image/webp
      mime_type: image/webp
      resize_style: contain
      width: 260
      height: 32
  price:
    type: number
  content:
    type: html
  name:
    hidden: true
  id:
    hidden: true

_structures:
  head:
    remove_empty_inputs: true
    id_key: title
    values:
      - label: SEO / Settings
        value:
          title: null
          description: null
          image: null
          code: null
_editables:
  content:
    allow_custom_markup: false
    remove_custom_markup: false
    bold: true
    bulletedlist: true
    format: p h1 h2 h3 h4 h5 h6
    image: true
    image_size_attributes: true
    italic: true
    link: true
    numberedlist: true
    redo: true
    table: true
    underline: true
    undo: true
    mime_type: image/webp
    resize_style: contain
    width: 1920
    height: 1920
