/** @type {import("prettier").Config} */
module.exports = {
  endOfLine: "lf",
  semi: false,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "es5",
  printWidth: 80,
  importOrder: [
    "^(astro/(.*)$)|^(astro:.*$)|^(astro$)",
    "<THIRD_PARTY_MODULES>",
    "",
    "^@/schemas/(.*)$",
    "^@/lib/(.*)$",
    "^@/layouts/(.*)$",
    "^@/components/blocks/(.*)$",
    "^@/components/ui/(.*)$",
    "^@/components/(.*)$",
    "^@/(.*)$",
    "",
    "^[./]",
  ],
  importOrderParserPlugins: ["typescript", "jsx"],
  plugins: [
    "prettier-plugin-astro",
    "@ianvs/prettier-plugin-sort-imports",
    "prettier-plugin-tailwindcss",
  ],
  tailwindStylesheet: "src/styles/global.css",
  tailwindFunctions: ["cn", "cva"],
  overrides: [{ files: "*.astro", options: { parser: "astro" } }],
}
