export { default as ReviewsCard } from './ReviewsCard.astro'
export { default as ReviewsDeck } from './ReviewsDeck.astro'
// export { default as ReviewsLayout } from './ReviewsLayout.astro'
export { default as ReviewsSection } from './ReviewsSection.astro'
export { default as reviewsSchema } from './reviews.schema'
