block: Product1
title: Earthen Mug
description: A mug for the modern age.
list:
  - Lorem ipsum dolor sit amet
  - Sed do eiusmod tempor incididunt
  - Ut enim ad minim veniam
images:
  - src: /images/products/earthen-mug.jpg
    alt: Earthen Mug
  - src: /images/products/earthen-mug.jpg
    alt: Earthen Mug
  - src: /images/products/leather-long-wallet.jpg
    alt: Earthen Mug
price: 28
categories:
  - productivity
