block: Products1
size: sm
title: Lorem ipsum dolor
button:
  text: Lorem ipsum
  href: '#'
products:
  - earthen-mug
  - leather-long-wallet
  - leatherbound-daily-journal-set
  - leatherbound-daily-journal
  - machines-pen
  - machines-pencil-and-pen-set
  - mini-sketchbooks
  - organizer-set
