import { z } from 'astro:content'

export const attributes = z.object({
  '*': z.enum([
    'accesskey',
    'autocapitalize',
    'autofocus',
    'class',
    'contenteditable',
    'dir',
    'draggable',
    'enterkeyhint',
    'hidden',
    'id',
    'inert',
    'inputmode',
    'is',
    'itemid',
    'itemprop',
    'itemref',
    'itemscope',
    'itemtype',
    'lang',
    'nonce',
    'popover',
    'slot',
    'spellcheck',
    'style',
    'tabindex',
    'title',
    'translate',
  ]),
  a: z.enum([
    'charset',
    'coords',
    'download',
    'href',
    'hreflang',
    'name',
    'ping',
    'referrerpolicy',
    'rel',
    'rev',
    'shape',
    'target',
    'type',
  ]),
  applet: z.enum([
    'align',
    'alt',
    'archive',
    'code',
    'codebase',
    'height',
    'hspace',
    'name',
    'object',
    'vspace',
    'width',
  ]),
  area: z.enum([
    'alt',
    'coords',
    'download',
    'href',
    'hreflang',
    'nohref',
    'ping',
    'referrerpolicy',
    'rel',
    'shape',
    'target',
    'type',
  ]),
  audio: z.enum([
    'autoplay',
    'controls',
    'crossorigin',
    'loop',
    'muted',
    'preload',
    'src',
  ]),
  base: z.enum(['href', 'target']),
  basefont: z.enum(['color', 'face', 'size']),
  blockquote: z.enum(['cite']),
  body: z.enum(['alink', 'background', 'bgcolor', 'link', 'text', 'vlink']),
  br: z.enum(['clear']),
  button: z.enum([
    'disabled',
    'form',
    'formaction',
    'formenctype',
    'formmethod',
    'formnovalidate',
    'formtarget',
    'name',
    'popovertarget',
    'popovertargetaction',
    'type',
    'value',
  ]),
  canvas: z.enum(['height', 'width']),
  caption: z.enum(['align']),
  col: z.enum(['align', 'char', 'charoff', 'span', 'valign', 'width']),
  colgroup: z.enum(['align', 'char', 'charoff', 'span', 'valign', 'width']),
  data: z.enum(['value']),
  del: z.enum(['cite', 'datetime']),
  details: z.enum(['name', 'open']),
  dialog: z.enum(['open']),
  dir: z.enum(['compact']),
  div: z.enum(['align']),
  dl: z.enum(['compact']),
  embed: z.enum(['height', 'src', 'type', 'width']),
  fieldset: z.enum(['disabled', 'form', 'name']),
  font: z.enum(['color', 'face', 'size']),
  form: z.enum([
    'accept',
    'accept-charset',
    'action',
    'autocomplete',
    'enctype',
    'method',
    'name',
    'novalidate',
    'target',
  ]),
  frame: z.enum([
    'frameborder',
    'longdesc',
    'marginheight',
    'marginwidth',
    'name',
    'noresize',
    'scrolling',
    'src',
  ]),
  frameset: z.enum(['cols', 'rows']),
  h1: z.enum(['align']),
  h2: z.enum(['align']),
  h3: z.enum(['align']),
  h4: z.enum(['align']),
  h5: z.enum(['align']),
  h6: z.enum(['align']),
  head: z.enum(['profile']),
  hr: z.enum(['align', 'noshade', 'size', 'width']),
  html: z.enum(['manifest', 'version']),
  iframe: z.enum([
    'align',
    'allow',
    'allowfullscreen',
    'allowpaymentrequest',
    'allowusermedia',
    'frameborder',
    'height',
    'loading',
    'longdesc',
    'marginheight',
    'marginwidth',
    'name',
    'referrerpolicy',
    'sandbox',
    'scrolling',
    'src',
    'srcdoc',
    'width',
  ]),
  img: z.enum([
    'align',
    'alt',
    'border',
    'crossorigin',
    'decoding',
    'fetchpriority',
    'height',
    'hspace',
    'ismap',
    'loading',
    'longdesc',
    'name',
    'referrerpolicy',
    'sizes',
    'src',
    'srcset',
    'usemap',
    'vspace',
    'width',
  ]),
  input: z.enum([
    'accept',
    'align',
    'alt',
    'autocomplete',
    'checked',
    'dirname',
    'disabled',
    'form',
    'formaction',
    'formenctype',
    'formmethod',
    'formnovalidate',
    'formtarget',
    'height',
    'ismap',
    'list',
    'max',
    'maxlength',
    'min',
    'minlength',
    'multiple',
    'name',
    'pattern',
    'placeholder',
    'popovertarget',
    'popovertargetaction',
    'readonly',
    'required',
    'size',
    'src',
    'step',
    'type',
    'usemap',
    'value',
    'width',
  ]),
  ins: z.enum(['cite', 'datetime']),
  isindex: z.enum(['prompt']),
  label: z.enum(['for', 'form']),
  legend: z.enum(['align']),
  li: z.enum(['type', 'value']),
  link: z.enum([
    'as',
    'blocking',
    'charset',
    'color',
    'crossorigin',
    'disabled',
    'fetchpriority',
    'href',
    'hreflang',
    'imagesizes',
    'imagesrcset',
    'integrity',
    'media',
    'referrerpolicy',
    'rel',
    'rev',
    'sizes',
    'target',
    'type',
  ]),
  map: z.enum(['name']),
  menu: z.enum(['compact']),
  meta: z.enum(['charset', 'content', 'http-equiv', 'media', 'name', 'scheme']),
  meter: z.enum(['high', 'low', 'max', 'min', 'optimum', 'value']),
  object: z.enum([
    'align',
    'archive',
    'border',
    'classid',
    'codebase',
    'codetype',
    'data',
    'declare',
    'form',
    'height',
    'hspace',
    'name',
    'standby',
    'type',
    'typemustmatch',
    'usemap',
    'vspace',
    'width',
  ]),
  ol: z.enum(['compact', 'reversed', 'start', 'type']),
  optgroup: z.enum(['disabled', 'label']),
  option: z.enum(['disabled', 'label', 'selected', 'value']),
  output: z.enum(['for', 'form', 'name']),
  p: z.enum(['align']),
  param: z.enum(['name', 'type', 'value', 'valuetype']),
  pre: z.enum(['width']),
  progress: z.enum(['max', 'value']),
  q: z.enum(['cite']),
  script: z.enum([
    'async',
    'blocking',
    'charset',
    'crossorigin',
    'defer',
    'fetchpriority',
    'integrity',
    'language',
    'nomodule',
    'referrerpolicy',
    'src',
    'type',
  ]),
  select: z.enum([
    'autocomplete',
    'disabled',
    'form',
    'multiple',
    'name',
    'required',
    'size',
  ]),
  slot: z.enum(['name']),
  source: z.enum([
    'height',
    'media',
    'sizes',
    'src',
    'srcset',
    'type',
    'width',
  ]),
  style: z.enum(['blocking', 'media', 'type']),
  table: z.enum([
    'align',
    'bgcolor',
    'border',
    'cellpadding',
    'cellspacing',
    'frame',
    'rules',
    'summary',
    'width',
  ]),
  tbody: z.enum(['align', 'char', 'charoff', 'valign']),
  td: z.enum([
    'abbr',
    'align',
    'axis',
    'bgcolor',
    'char',
    'charoff',
    'colspan',
    'headers',
    'height',
    'nowrap',
    'rowspan',
    'scope',
    'valign',
    'width',
  ]),
  template: z.enum(['shadowrootdelegatesfocus', 'shadowrootmode']),
  textarea: z.enum([
    'autocomplete',
    'cols',
    'dirname',
    'disabled',
    'form',
    'maxlength',
    'minlength',
    'name',
    'placeholder',
    'readonly',
    'required',
    'rows',
    'wrap',
  ]),
  tfoot: z.enum(['align', 'char', 'charoff', 'valign']),
  th: z.enum([
    'abbr',
    'align',
    'axis',
    'bgcolor',
    'char',
    'charoff',
    'colspan',
    'headers',
    'height',
    'nowrap',
    'rowspan',
    'scope',
    'valign',
    'width',
  ]),
  thead: z.enum(['align', 'char', 'charoff', 'valign']),
  time: z.enum(['datetime']),
  tr: z.enum(['align', 'bgcolor', 'char', 'charoff', 'valign']),
  track: z.enum(['default', 'kind', 'label', 'src', 'srclang']),
  ul: z.enum(['compact', 'type']),
  video: z.enum([
    'autoplay',
    'controls',
    'crossorigin',
    'height',
    'loop',
    'muted',
    'playsinline',
    'poster',
    'preload',
    'src',
    'width',
  ]),
})
