name: 'Bug report'
description: Report a bug or issue
labels: ['bug']
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug or issue
      description: Be clear and concise. Add logs and/or screenshots if applicable.
      placeholder: Add your bug or issue description here...
    validations:
      required: true
