blank_issues_enabled: false
contact_links:
  - name: Add your site to our showcase
    url: https://github.com/fulldotdev/ui/blob/main/CONTRIBUTING.md#showcase
    about: Add your project to the showcase page and get featured on our website.
  - name: Get Help on Discord
    url: https://discord.gg/tdmUyH2YE4
    about: If you can't get something to work, open a forum post in our Discord server.
