name: 'Documentation'
description: Issues and suggestions regarding documentation
labels: ['docs']
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the issue or suggestion
      description: Be clear and concise. Add logs and/or screenshots if applicable.
      placeholder: Add your issue or suggestion description here...
    validations:
      required: true
