name: 'Feature'
description: Propose and discuss improvements
labels: ['feature']
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: Be clear and concise. Add logs and/or screenshots if applicable.
      placeholder: Add your feature description here...
    validations:
      required: true
