name: 'Support'
description: Ask a question or request help
labels: ['support']
body:
  - type: textarea
    id: description
    attributes:
      label: Describe your question or request
      description: Be clear and concise. Add logs and/or screenshots if applicable.
      placeholder: Add your question or request description here...
    validations:
      required: true
