spec: #1
  structures:
    - sections
  label: Features

blueprint: #2
  html: "<h2>Features</h2>"
  links:
    - text: "Learn more"
      href: "#"
  features:
    - icon: "check"
      title: "Feature 1"
      description: "Description 1"
      link:
        text: "Learn more"
        href: "#"

preview: #3

_inputs: #4
