seo:
  image: /images/og-image.png

code:
  head: |
    <script is:inline>
      !function(t,e){var o,n,p,r;e.__SV||(window.posthog=e,e._i=[],e.init=function(i,s,a){function g(t,e){var o=e.split(".");2==o.length&&(t=t[o[0]],e=o[1]),t[e]=function(){t.push([e].concat(Array.prototype.slice.call(arguments,0)))}}(p=t.createElement("script")).type="text/javascript",p.crossOrigin="anonymous",p.async=!0,p.src=s.api_host.replace(".i.posthog.com","-assets.i.posthog.com")+"/static/array.js",(r=t.getElementsByTagName("script")[0]).parentNode.insertBefore(p,r);var u=e;for(void 0!==a?u=e[a]=[]:a="posthog",u.people=u.people||[],u.toString=function(t){var e="posthog";return"posthog"!==a&&(e+="."+a),t||(e+=" (stub)"),e},u.people.toString=function(){return u.toString(1)+".people (stub)"},o="init capture register register_once register_for_session unregister unregister_for_session getFeatureFlag getFeatureFlagPayload isFeatureEnabled reloadFeatureFlags updateEarlyAccessFeatureEnrollment getEarlyAccessFeatures on onFeatureFlags onSessionId getSurveys getActiveMatchingSurveys renderSurvey canRenderSurvey getNextSurveyStep identify setPersonProperties group resetGroups setPersonPropertiesForFlags resetPersonPropertiesForFlags setGroupPropertiesForFlags resetGroupPropertiesForFlags reset get_distinct_id getGroups get_session_id get_session_replay_url alias set_config startSessionRecording stopSessionRecording sessionRecordingStarted captureException loadToolbar get_property getSessionProperty createPersonProfile opt_in_capturing opt_out_capturing has_opted_in_capturing has_opted_out_capturing clear_opt_in_out_capturing debug".split(" "),n=0;n<o.length;n++)g(u,o[n]);e._i.push([i,s,a])},e.__SV=1)}(document,window.posthog||[]);
      posthog.init('phc_mVacbe8Xydu0UZlh4bNw5EGisvzyRcpqXEEuEEp5lOY',{api_host:'https://eu.i.posthog.com', person_profiles: 'identified_only' // or 'always' to create profiles for anonymous users as well
        })
    </script>

header: true
navigation:
  company: Fulldev UI
  buttons:
    - text: Docs
      href: /overview/introduction
    - text: Components
      href: /typography/heading
    - text: Blocks
      href: /blocks/banner
    - showcase
    - href: https://github.com/fulldotdev/ui
      target: _blank
      icon: brand-github
      variant: secondary
    - href: https://discord.gg/vXZqMbadm8
      target: _blank
      icon: brand-discord
      variant: secondary
  menu:
    - heading: Get Started
      buttons:
        - overview/introduction
        - overview/installation
        - overview/theming
        - overview/frameworks
        - overview/components
        - overview/content-collections
    - heading: Typography
      buttons:
        - typography/heading
        - typography/label
        - typography/link
        - typography/list
        - typography/text
    - heading: Base
      buttons:
        - base/badge
        - base/button
        - base/card
        - base/checkbox
        - base/icon
        - base/input
        - base/rating
        - base/section
        - base/select
        - base/table
        - base/textarea
        - base/theme-select
        - base/image
    - heading: Blocks
      buttons:
        - blocks/banner
        - blocks/colleagues
        - blocks/contact
        - blocks/content
        - blocks/cta
        - blocks/features
        - blocks/hero
        - blocks/intro
        - blocks/posts
        - blocks/product
        - blocks/reviews
    - heading: Schemas
      buttons:
        - schemas/page
        - schemas/preset
    - heading: More
      buttons:
        - showcase
        - text: Changelog
          href: https://github.com/fulldotdev/ui/releases
