seo:
  image: /images/og-image.png

header:
  heading: Fulldev UI
  search: true
  links:
    - text: Docs
      href: /overview/introduction
    - text: Components
      href: /typography/heading
    - blocks
    - showcase
  buttons:
    - href: https://github.com/fulldotdev/ui
      target: _blank
      icon: brand-github
    - href: https://discord.gg/vXZqMbadm8
      target: _blank
      icon: brand-discord
