seo:
  image: /images/og-image.png

code:
  head: |
    <script is:inline>
      !function(t,e){var o,n,p,r;e.__SV||(window.posthog=e,e._i=[],e.init=function(i,s,a){function g(t,e){var o=e.split(".");2==o.length&&(t=t[o[0]],e=o[1]),t[e]=function(){t.push([e].concat(Array.prototype.slice.call(arguments,0)))}}(p=t.createElement("script")).type="text/javascript",p.crossOrigin="anonymous",p.async=!0,p.src=s.api_host.replace(".i.posthog.com","-assets.i.posthog.com")+"/static/array.js",(r=t.getElementsByTagName("script")[0]).parentNode.insertBefore(p,r);var u=e;for(void 0!==a?u=e[a]=[]:a="posthog",u.people=u.people||[],u.toString=function(t){var e="posthog";return"posthog"!==a&&(e+="."+a),t||(e+=" (stub)"),e},u.people.toString=function(){return u.toString(1)+".people (stub)"},o="init capture register register_once register_for_session unregister unregister_for_session getFeatureFlag getFeatureFlagPayload isFeatureEnabled reloadFeatureFlags updateEarlyAccessFeatureEnrollment getEarlyAccessFeatures on onFeatureFlags onSessionId getSurveys getActiveMatchingSurveys renderSurvey canRenderSurvey getNextSurveyStep identify setPersonProperties group resetGroups setPersonPropertiesForFlags resetPersonPropertiesForFlags setGroupPropertiesForFlags resetGroupPropertiesForFlags reset get_distinct_id getGroups get_session_id get_session_replay_url alias set_config startSessionRecording stopSessionRecording sessionRecordingStarted captureException loadToolbar get_property getSessionProperty createPersonProfile opt_in_capturing opt_out_capturing has_opted_in_capturing has_opted_out_capturing clear_opt_in_out_capturing debug".split(" "),n=0;n<o.length;n++)g(u,o[n]);e._i.push([i,s,a])},e.__SV=1)}(document,window.posthog||[]);
      posthog.init('phc_mVacbe8Xydu0UZlh4bNw5EGisvzyRcpqXEEuEEp5lOY',{api_host:'https://eu.i.posthog.com', person_profiles: 'identified_only' // or 'always' to create profiles for anonymous users as well
        })
    </script>
sidebar: true
toc: false
themeselect: true

header:
  company: Fulldev UI
  buttons:
    - text: Docs
      href: /overview/introduction
    - text: Components
      href: /typography/heading
    - text: Blocks
      href: /blocks/banner
    - showcase
    - href: https://github.com/fulldotdev/ui
      target: _blank
      icon: brand-github
      variant: secondary
    - href: https://discord.gg/vXZqMbadm8
      target: _blank
      icon: brand-discord
      variant: secondary
# footer:
#   logo: Fulldev UI
#   text: The Astro UI library to build content sites. Make websites with prebuilt components, blocks and layouts.
#   columns:
#     - heading: Pages
#       buttons:
#         - text: Docs
#           href: /overview/introduction
#         - text: Components
#           href: /typography/heading
#         - blocks
#         - showcase
#   socials:
#     - https://www.linkedin.com/in/silveltman/
#     - https://x.com/silveltm
#     - https://github.com/fulldotdev/ui
#   channels:
#     - heading: Phone
#       text: 123-456-7890
#       icon: phone
#       href: tel:123-456-7890
#     - heading: Email
#       text: contact@example.com
#       icon: mail
#       href: mailto:contact@example.com
#     - heading: Address
#       text: 1234 Main St, Springfield, IL 62701
#       icon: map-pin
#   hours:
#     heading: Openingstijden
#     days:
#       ma.: 09:00 - 17:00
#       di.: 09:00 - 17:00
#       wo.: 09:00 - 17:00
#       do.: 09:00 - 17:00
#       vr.: 09:00 - 17:00
#       za.: 09:00 - 17:00
#       zo.: 09:00 - 17:00
