seo:
  image: /images/og-image.png

navigation:
  logo: Fulldev UI
  buttons:
    - text: Docs
      href: /overview/introduction
    - text: Components
      href: /typography/heading
    - blocks
    - showcase
    - href: https://github.com/fulldotdev/ui
      target: _blank
      icon: brand-github
      variant: secondary
    - href: https://discord.gg/vXZqMbadm8
      target: _blank
      icon: brand-discord
      variant: secondary
