seo:
  image: /images/og-image.png

sidebar: false
toc: false

navigation:
  logo: Fulldev UI
  buttons:
    - text: Docs
      href: /overview/introduction
    - text: Components
      href: /typography/heading
    - blocks
    - showcase
    - href: https://github.com/fulldotdev/ui
      target: _blank
      icon: brand-github
      variant: secondary
    - href: https://discord.gg/vXZqMbadm8
      target: _blank
      icon: brand-discord
      variant: secondary
# footer:
#   logo: Fulldev UI
#   text: The Astro UI library to build content sites. Make websites with prebuilt components, blocks and layouts.
#   columns:
#     - heading: Pages
#       buttons:
#         - text: Docs
#           href: /overview/introduction
#         - text: Components
#           href: /typography/heading
#         - blocks
#         - showcase
#   socials:
#     - https://www.linkedin.com/in/silveltman/
#     - https://x.com/silveltm
#     - https://github.com/fulldotdev/ui
#   channels:
#     - heading: Phone
#       text: 123-456-7890
#       icon: phone
#       href: tel:123-456-7890
#     - heading: Email
#       text: contact@example.com
#       icon: mail
#       href: mailto:contact@example.com
#     - heading: Address
#       text: 1234 Main St, Springfield, IL 62701
#       icon: map-pin
#   hours:
#     heading: Openingstijden
#     days:
#       ma.: 09:00 - 17:00
#       di.: 09:00 - 17:00
#       wo.: 09:00 - 17:00
#       do.: 09:00 - 17:00
#       vr.: 09:00 - 17:00
#       za.: 09:00 - 17:00
#       zo.: 09:00 - 17:00
