seo:
  image: /images/og-image.png

navigation:
  logo: Fulldev UI
  search: false
  buttons:
    - text: Docs
      href: /overview/introduction
    - text: Components
      href: /typography/heading
    - blocks
    - showcase
    - href: https://github.com/fulldotdev/ui
      target: _blank
      icon: brand-github
      variant: secondary
    - href: https://discord.gg/vXZqMbadm8
      target: _blank
      icon: brand-discord
      variant: secondary

footer:
  logo: Fulldev UI
  text: The Astro UI library to build content sites. Make websites with prebuilt components, blocks and layouts.
  columns:
    - heading: Docs
      buttons:
        - text: Docs
          href: /overview/introduction
        - text: Components
          href: /typography/heading
        - blocks
        - showcase
    - heading: Test
      buttons:
        - text: Docs
          href: /overview/introduction
        - text: Components
          href: /typography/heading
        - blocks
        - showcase
  socials:
    - https://www.linkedin.com/in/silveltman/
    - https://x.com/silveltm
    - https://github.com/fulldotdev/ui
  hours:
    heading: Openingstijden
    days:
      maandag: 09:00 - 17:00
      dinsdag: 09:00 - 17:00
      woensdag: 09:00 - 17:00
      donderdag: 09:00 - 17:00
      vrijdag: 09:00 - 17:00
      zaterdag: 09:00 - 17:00
      zondag: 09:00 - 17:00
  # links:
  #   - text: Docs
  #     href: /overview/introduction
  #   - text: Components
  #     href: /typography/heading
