import { z } from 'zod';

export const attributesSchema = z.object({
  abbr: z.any(),
  accept: z.any(),
  acceptCharset: z.any(),
  accessKey: z.any(),
  // action: z.any(),
  allowFullScreen: z.any(),
  allowTransparency: z.any(),
  alt: z.any(),
  async: z.any(),
  autoComplete: z.any(),
  autoFocus: z.any(),
  autoPlay: z.any(),
  cellPadding: z.any(),
  cellSpacing: z.any(),
  challenge: z.any(),
  charset: z.any(),
  checked: z.any(),
  cite: z.any(),
  class: z.any(),
  className: z.any(),
  cols: z.any(),
  colSpan: z.any(),
  command: z.any(),
  content: z.any(),
  contentEditable: z.any(),
  contextMenu: z.any(),
  controls: z.any(),
  coords: z.any(),
  crossOrigin: z.any(),
  data: z.any(),
  dateTime: z.any(),
  default: z.any(),
  defer: z.any(),
  dir: z.any(),
  disabled: z.any(),
  download: z.any(),
  draggable: z.any(),
  dropzone: z.any(),
  encType: z.any(),
  for: z.any(),
  form: z.any(),
  action: z.any(),
  formEncType: z.any(),
  method: z.any(),
  formNoValidate: z.any(),
  target: z.any(),
  frameBorder: z.any(),
  headers: z.any(),
  height: z.any(),
  hidden: z.any(),
  high: z.any(),
  href: z.any(),
  hrefLang: z.any(),
  htmlFor: z.any(),
  httpEquiv: z.any(),
  // icon: z.any(),
  id: z.any(),
  inputMode: z.any(),
  isMap: z.any(),
  itemId: z.any(),
  itemProp: z.any(),
  itemRef: z.any(),
  itemScope: z.any(),
  itemType: z.any(),
  kind: z.any(),
  label: z.any(),
  lang: z.any(),
  list: z.any(),
  loop: z.any(),
  manifest: z.any(),
  max: z.any(),
  maxLength: z.any(),
  media: z.any(),
  mediaGroup: z.any(),
  min: z.any(),
  minLength: z.any(),
  multiple: z.any(),
  muted: z.any(),
  name: z.any(),
  noValidate: z.any(),
  open: z.any(),
  optimum: z.any(),
  pattern: z.any(),
  ping: z.any(),
  placeholder: z.any(),
  poster: z.any(),
  preload: z.any(),
  // radioGroup: z.any(),
  // readOnly: z.any(),
  rel: z.any(),
  required: z.any(),
  // role: z.any(),
  rows: z.any(),
  // rowSpan: z.any(),
  // sandbox: z.any(),
  // scope: z.any(),
  // scoped: z.any(),
  // scrolling: z.any(),
  // seamless: z.any(),
  // selected: z.any(),
  // shape: z.any(),
  // size: z.any(),
  sizes: z.any(),
  // sortable: z.any(),
  // span: z.any(),
  // spellCheck: z.any(),
  src: z.any(),
  // srcDoc: z.any(),
  srcset: z.any(),
  // start: z.any(),
  // step: z.any(),
  style: z.any(),
  tabIndex: z.any(),
  // title: z.any(),
  // translate: z.any(),
  type: z.any(),
  // typeMustMatch: z.any(),
  // useMap: z.any(),
  value: z.any(),
  width: z.any(),
  // wmode: z.any(),
  // wrap: z.any(),
});
