export { default as Banner } from './components/blocks/Banner.astro'
export { default as Categories } from './components/blocks/Categories.astro'
export { default as Content } from './components/blocks/Content.astro'
export { default as Cta } from './components/blocks/Cta.astro'
export { default as Employees } from './components/blocks/Employees.astro'
export { default as Features } from './components/blocks/Features.astro'
export { default as Footer } from './components/blocks/Footer.astro'
export { default as Header } from './components/blocks/Header.astro'
export { default as Hero } from './components/blocks/Hero.astro'
export { default as Intro } from './components/blocks/Intro.astro'
export { default as Logos } from './components/blocks/Logos.astro'
export { default as Missing } from './components/blocks/Missing.astro'
export { default as Newsletter } from './components/blocks/Newsletter.astro'
export { default as Posts } from './components/blocks/Posts.astro'
export { default as Prices } from './components/blocks/Prices.astro'
export { default as Product } from './components/blocks/Product.astro'
export { default as Products } from './components/blocks/Products.astro'
export { default as Reviews } from './components/blocks/Reviews.astro'
export { default as Stats } from './components/blocks/Stats.astro'

// Layouts
// export { default as CategoryLayout } from './layouts/CategoryLayout.astro'
export { default as Layout } from './layouts/Layout.astro'
export { default as NavLayout } from './layouts/NavLayout.astro'
export { default as PageLayout } from './layouts/PageLayout.astro'
export { default as PolicyLayout } from './layouts/PolicyLayout.astro'
export { default as PostLayout } from './layouts/PostLayout.astro'
export { default as ProductLayout } from './layouts/ProductLayout.astro'
export { default as ProductsLayout } from './layouts/ProductsLayout.astro'
