lang: nl
title: Lorem Ipsum
image:
  src: /images/logo.png
  alt: Lorem Ipsum
company: Lorem Ipsum
banner:
  variant: 1
  list:
    - Lorem
    - Ipsum
    - Dolor
header:
  variant: 1
  logo:
    src: /images/logo.png
    alt: Logo Lorem
  menus:
    - text: Home
      href: /
    - text: Lorem ipsum
      links:
        - text: Lorem ipsum
          href: "#"
        - text: Lorem ipsum
          href: "#"
footer:
  variant: 0
  logo:
    src: /images/logo.png
    alt: Logo Lorem
  menus:
    - text: Lorem ipsum
      links:
        - text: Lorem ipsum
          href: "#"
        - text: Lorem ipsum
          href: "#"
        - text: Lorem ipsum
          href: "#"
head: ""
body: ""
css: ""
