head:
  title: Fulldev UI - Astro component and block library, open-source
  image:
    src: /images/og-image.png
  theme: system
  code: |
    <script is:inline>
      !function(t,e){var o,n,p,r;e.__SV||(window.posthog=e,e._i=[],e.init=function(i,s,a){function g(t,e){var o=e.split(".");2==o.length&&(t=t[o[0]],e=o[1]),t[e]=function(){t.push([e].concat(Array.prototype.slice.call(arguments,0)))}}(p=t.createElement("script")).type="text/javascript",p.crossOrigin="anonymous",p.async=!0,p.src=s.api_host.replace(".i.posthog.com","-assets.i.posthog.com")+"/static/array.js",(r=t.getElementsByTagName("script")[0]).parentNode.insertBefore(p,r);var u=e;for(void 0!==a?u=e[a]=[]:a="posthog",u.people=u.people||[],u.toString=function(t){var e="posthog";return"posthog"!==a&&(e+="."+a),t||(e+=" (stub)"),e},u.people.toString=function(){return u.toString(1)+".people (stub)"},o="init capture register register_once register_for_session unregister unregister_for_session getFeatureFlag getFeatureFlagPayload isFeatureEnabled reloadFeatureFlags updateEarlyAccessFeatureEnrollment getEarlyAccessFeatures on onFeatureFlags onSessionId getSurveys getActiveMatchingSurveys renderSurvey canRenderSurvey getNextSurveyStep identify setPersonProperties group resetGroups setPersonPropertiesForFlags resetPersonPropertiesForFlags setGroupPropertiesForFlags resetGroupPropertiesForFlags reset get_distinct_id getGroups get_session_id get_session_replay_url alias set_config startSessionRecording stopSessionRecording sessionRecordingStarted captureException loadToolbar get_property getSessionProperty createPersonProfile opt_in_capturing opt_out_capturing has_opted_in_capturing has_opted_out_capturing clear_opt_in_out_capturing debug".split(" "),n=0;n<o.length;n++)g(u,o[n]);e._i.push([i,s,a])},e.__SV=1)}(document,window.posthog||[]);
      posthog.init('phc_mVacbe8Xydu0UZlh4bNw5EGisvzyRcpqXEEuEEp5lOY',{api_host:'https://eu.i.posthog.com', person_profiles: 'identified_only' // or 'always' to create profiles for anonymous users as well
        })
    </script>

banner:
  text: 'Introducing v0.6: build complete websites 🎉'

header:
  search: true
  themer: true
  logo:
    image: /favicon/android-chrome-512x512.png
    text: Fulldev UI
  links:
    - text: Docs
      href: /docs/
    - text: Components
      href: /docs/components/badge/
    - text: Structures
      href: /docs/structures/container/
    - text: Blocks
      href: /docs/blocks/banner/
  socials:
    - https://github.com/fulldotdev/ui
    - https://discord.gg/vXZqMbadm8

menus:
  - heading: Get Started
    links:
      - text: Introduction
        href: /docs/
      - text: Installation
        href: /docs/installation/
      - text: Customization
        href: /docs/customization/
      - text: Integrating frameworks
        href: /docs/frameworks/
      - text: Using components
        href: /docs/components/
      - text: Using structures
        href: /docs/structures/
      - text: Using blocks
        href: /docs/blocks/
  - heading: Components
    links:
      - text: Avatar
        href: /docs/components/avatar/
      - text: Avatars
        href: /docs/components/avatars/
      - text: Badge
        href: /docs/components/badge/
      # - text: Badges
      #   href: /docs/components/badges/
      - text: Button
        href: /docs/components/button/
      # - text: Buttons
      #   href: /docs/components/buttons/
      - text: Channel
        href: /docs/components/channel/
      # - text: Channels
      #   href: /docs/components/channels/
      - text: Checkbox
        href: /docs/components/checkbox/
      - text: Heading
        href: /docs/components/heading/
      - text: Icon
        href: /docs/components/icon/
      - text: Image
        href: /docs/components/image/
      - text: Input
        href: /docs/components/input/
      - text: Label
        href: /docs/components/label/
      - text: Link
        href: /docs/components/link/
      - text: Links
        href: /docs/components/links/
      - text: List
        href: /docs/components/list/
      - text: Logo
        href: /docs/components/logo/
      - text: Menu
        href: /docs/components/menu/
      - text: Paragraph
        href: /docs/components/paragraph/
      - text: Rating
        href: /docs/components/rating/
      - text: Select
        href: /docs/components/select/
      - text: Social
        href: /docs/components/social/
      - text: Socials
        href: /docs/components/socials/
      - text: Switch
        href: /docs/components/switch/
      - text: Tagline
        href: /docs/components/tagline/
      - text: Textarea
        href: /docs/components/textarea/
  - heading: Structures
    links:
      - text: Card
        href: /docs/structures/card/
      - text: Carousel
        href: /docs/structures/carousel/
      - text: Code
        href: /docs/structures/code/
      - text: Container
        href: /docs/structures/container/
      - text: Drawer
        href: /docs/structures/drawer/
      - text: Group
        href: /docs/structures/group/
      - text: Layout
        href: /docs/structures/layout/
      - text: Masonry
        href: /docs/structures/masonry/
      - text: Matrix
        href: /docs/structures/matrix/
      - text: Panel
        href: /docs/structures/panel/
      - text: Prose
        href: /docs/structures/prose/
      - text: Section
        href: /docs/structures/section/
      - text: Sidebar
        href: /docs/structures/sidebar/
      - text: Split
        href: /docs/structures/split/
      - text: Stack
        href: /docs/structures/stack/
  - heading: Blocks
    links:
      - text: Banner
        href: /docs/blocks/banner/
      - text: Colleagues
        href: /docs/blocks/colleagues/
      - text: Content
        href: /docs/blocks/content/
      - text: Cta
        href: /docs/blocks/cta/
      - text: Features
        href: /docs/blocks/features/
      - text: Footer
        href: /docs/blocks/footer/
      - text: Header
        href: /docs/blocks/header/
      - text: Hero
        href: /docs/blocks/hero/
      - text: Intro
        href: /docs/blocks/intro/
      - text: Logos
        href: /docs/blocks/logos/
      - text: Reviews
        href: /docs/blocks/reviews/
      - text: Projects
        href: /docs/blocks/projects/

footer:
  menus: []
