// Write Fulldev versions of shadcn/ui placeholders, for components whose markup
// exposes state through different attributes than Base UI. Each cn-fd-* class
// copies a shadcn/ui placeholder per style and rewrites its selectors, so it
// follows upstream style changes. Output: registry/styles/adapted/style-<name>.css
import { mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { createStyleMap } from "shadcn/utils"

import { STYLES } from "./styles.mjs"

// Menus highlight items with data-highlighted instead of focus.
const highlighted = [
  [/(^|[\s:])focus:/g, "$1data-highlighted:"],
  [/group-focus\//g, "group-data-highlighted/"],
]

// Toggle group items take variant and size from the group.
const fromGroup = (attribute) => [
  [/(^|\s)(?=\S)/g, `$1group-data-[${attribute}]/toggle-group:`],
]

const ADAPTED = {
  "cn-fd-checkbox": [
    "cn-checkbox",
    [
      [/data-checked:/g, "checked:"],
      [/aria-checked:/g, "checked:"],
    ],
  ],
  "cn-fd-tabs-trigger": [
    "cn-tabs-trigger",
    [[/data-active:/g, "data-[state=active]:"]],
  ],
  "cn-fd-dropdown-menu-item": ["cn-dropdown-menu-item", highlighted],
  "cn-fd-dropdown-menu-checkbox-item": [
    "cn-dropdown-menu-checkbox-item",
    highlighted,
  ],
  "cn-fd-dropdown-menu-radio-item": [
    "cn-dropdown-menu-radio-item",
    highlighted,
  ],
  "cn-fd-dropdown-menu-sub-trigger": [
    "cn-dropdown-menu-sub-trigger",
    highlighted,
  ],
  "cn-fd-dropdown-menu-shortcut": ["cn-dropdown-menu-shortcut", highlighted],
  "cn-fd-command-group": [
    "cn-command-group",
    [
      [
        /\*\*:\[\[cmdk-group-heading\]\]:/g,
        "[&_[data-slot=command-group-heading]]:",
      ],
    ],
  ],
  // Items read spacing from the group instead of their own attribute.
  "cn-fd-toggle-group-item": [
    "cn-toggle-group-item",
    [
      [
        /(?<!group-)data-\[spacing=0\]:/g,
        "group-data-[spacing=0]/toggle-group:",
      ],
    ],
  ],
  // The arrow is positioned by the component, only its shape follows the style.
  "cn-fd-tooltip-arrow": [
    "cn-tooltip-arrow",
    [[/\S*translate-[xy]-\[[^\]]*\]/g, ""]],
  ],
  "cn-fd-toggle-group-item-variant-outline": [
    "cn-toggle-variant-outline",
    fromGroup("variant=outline"),
  ],
  "cn-fd-toggle-group-item-size-default": [
    "cn-toggle-size-default",
    fromGroup("size=default"),
  ],
  "cn-fd-toggle-group-item-size-sm": [
    "cn-toggle-size-sm",
    fromGroup("size=sm"),
  ],
  "cn-fd-toggle-group-item-size-lg": [
    "cn-toggle-size-lg",
    fromGroup("size=lg"),
  ],
  // Addons pad the input group control, which is not always an <input>.
  "cn-fd-input-group": [
    "cn-input-group",
    [
      [
        /(has-\[>\[data-align=inline-(?:start|end)\]\]:)\[&>input\]/g,
        "$1[&>[data-slot=input-group-control]]",
      ],
    ],
  ],
  // The command input grows with flex-1 instead.
  "cn-fd-command-input": [
    "cn-command-input",
    [[/(^|\s)w-full(?=\s|$)/g, "$1"]],
  ],
  // Keeps the drawer shadow for styles that do not set one.
  "cn-fd-drawer-popup": [
    "cn-drawer-popup",
    [(value) => (/(^|\s)shadow-/.test(value) ? value : `${value} shadow-lg`)],
  ],
  // Choice cards also react to a native checked checkbox.
  "cn-fd-field-label": [
    "cn-field-label",
    [[/(^|[\s:])has-data-checked:/g, "$1has-[[data-checked],:checked]:"]],
  ],
  "cn-fd-select-item": [
    "cn-select-item",
    [...highlighted, [/\*:\[span\]:last:/g, "*:data-[slot=select-item-text]:"]],
  ],
}

const read = (path) => readFileSync(new URL(path, import.meta.url), "utf8")
mkdirSync(new URL("../registry/styles/adapted/", import.meta.url), {
  recursive: true,
})

// Adapted placeholders whose rewrites changed the upstream classes in a style.
const matched = new Set()

for (const style of STYLES) {
  const map = createStyleMap(
    read(`../registry/styles/shadcn/style-${style}.css`)
  )
  const rules = Object.entries(ADAPTED).flatMap(([name, [from, rewrites]]) => {
    if (!map[from]) return []
    const classes = rewrites
      .reduce(
        (value, rewrite) =>
          typeof rewrite === "function"
            ? rewrite(value)
            : value.replace(rewrite[0], rewrite[1]),
        map[from]
      )
      .replace(/\s+/g, " ")
      .trim()
    if (classes !== map[from].replace(/\s+/g, " ").trim()) matched.add(name)
    return [`  .${name} {\n    @apply ${classes};\n  }`]
  })
  writeFileSync(
    new URL(`../registry/styles/adapted/style-${style}.css`, import.meta.url),
    `/* Generated by scripts/registry-adapt.mjs. Do not edit. */\n.style-${style} {\n${rules.join("\n\n")}\n}\n`
  )
}

// A rewrite that matches in no style means upstream renamed the selector.
const unmatched = Object.keys(ADAPTED).filter((name) => !matched.has(name))
if (unmatched.length) {
  console.error(
    `Adapted placeholders with no matching upstream classes: ${unmatched.join(", ")}`
  )
  process.exit(1)
}
